package hc.lexer

enum class TokType {
    
    INT, LONG, FLOAT, DOUBLE, STRING, IDENT,

    ISTRING_BEGIN, ISTRING_PART, ISTRING_END,
    
    FN, STRUCT, LET, VAR, IF, ELSE, WHILE, FOR, IN, RETURN, TRUE, FALSE, IMPL, MUT, ARENA,
    INTERFACE, DYN, ENUM, MATCH, BY, SEALED, EXTERN, CLASS, MODULE, PUB, OPEN, EXTEND, STATIC, AS,
    TRY, CATCH, THROW, EXTENDS, OVERRIDE, NULL, IS,

    BREAK, CONTINUE,

    DEV,
    
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, COMMA, COLON, COLONCOLON, ARROW, FATARROW, SEMI, DOT, DOTDOT,

    DOTDOTEQ,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    EQ, EQEQ, BANGEQ, LT, LTEQ, GT, GTEQ, BANG, AMP, AMPAMP, PIPE, PIPEPIPE, QUESTION, AT,

    DOC_COMMENT,
    EOF
}

data class Token(val type: TokType, val text: String, val line: Int)
